# Morgan Stanley makes this available to you under the Apache License, Version 2.0 (the "License"). You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0. See the NOTICE file distributed with this work for additional information regarding copyright ownership. Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.  

# This workflow will do a clean install of node dependencies, build the source code and run tests

name: Prototypes-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]
        node-version: [ '18.x' ]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Install Nuget dependencies
      run: Get-ChildItem -Recurse -Include *.sln | ForEach-Object {dotnet restore $_} 
      working-directory: Tryouts
    - name: Build .Net
      run: Get-ChildItem -Recurse -Include *.sln | ForEach-Object {dotnet build $_ --configuration Release --no-restore; if ($LASTEXITCODE -ne 0 ) {throw "Build for $_ FAILED"; }} 
      working-directory: Tryouts
    - name: Test .Net
      run: Get-ChildItem -Recurse -Include *.sln | ForEach-Object {dotnet test $_ --no-restore --verbosity normal}  
      working-directory: Tryouts

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install NPM dependencies
      run: npm ci
      working-directory: Tryouts
    - name: Build JavaScript
      run: npx lerna run build
      working-directory: Tryouts
    - name: Test JavaScript
      run: npx lerna run test
      working-directory: Tryouts