name: Publish Package to npmjs

on:
  release:
    types: [published]
jobs:
  build:
    uses: ./.github/workflows/continuous-integration-prototypes.yml
  deploy-npm:
    name: Deploy packages to NPM
    needs: build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: [ '18.x' ]
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npx lerna run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}