on:
  release:
    types: [ published ]
    branches: [ main ]

  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  actions: read

name: Release

jobs:
  build:
    uses: ./.github/workflows/continuous-integration.yml
  upload:
    name: Upload Release Asset
    needs: build
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      # Using shared artifact from build workflow
      - name: Download Artifact
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: shell-binaries
          path: ${{ github.workspace }}/shell-binaries
    
      - name: Display structure of downloaded files
        run: Get-ChildItem -Recurse
        working-directory: ${{ github.workspace }}/shell-binaries
        
      - name: Compress
        run: Compress-Archive -Path  ${{ github.workspace }}/shell-binaries/* composeui-${{ github.ref_name }}-win32.zip
        
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./composeui-${{ github.ref_name }}-win32.zip
          asset_name: composeui-${{ github.ref_name }}-win32.zip
          asset_content_type: application/zip
          
  deploy-npm:
    name: Publish Package to npmjs
    runs-on: windows-latest
    needs: upload
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: 24.x
          registry-url: https://registry.npmjs.org/
      - run: |
             npm ci
             lerna run build --stream
             lerna publish from-package --loglevel verbose --no-private --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
          COMPOSEUI_SKIP_DOWNLOAD: 'true'

  deploy-nuget:
    name: Publish Nuget packages to nuget.org
    runs-on: windows-latest
    needs: build
    env:
      nuget_source: https://api.nuget.org/v3/index.json
    steps:
      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: packages
          path: ./packages
      - uses: actions/setup-dotnet@2016bd2012dba4e32de620c46fe006a3ac9f0602 # v5.0.1
        with:
          dotnet-version: 8.0.x
      - name: Publish Nuget packages
        working-directory: ./packages
        run: |
             dotnet nuget push MorganStanley.ComposeUI.Messaging.Core.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ env.nuget_source }} --skip-duplicate
             dotnet nuget push MorganStanley.ComposeUI.Messaging.Server.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ env.nuget_source }} --skip-duplicate
             dotnet nuget push MorganStanley.ComposeUI.Messaging.Client.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ env.nuget_source }} --skip-duplicate
             dotnet nuget push MorganStanley.ComposeUI.Messaging.Host.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ env.nuget_source }} --skip-duplicate
             dotnet nuget push MorganStanley.ComposeUI.Messaging.Abstractions.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ env.nuget_source }} --skip-duplicate
             dotnet nuget push MorganStanley.ComposeUI.Fdc3.AppDirectory.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ env.nuget_source }} --skip-duplicate
             dotnet nuget push MorganStanley.ComposeUI.Fdc3.DesktopAgent.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ env.nuget_source }} --skip-duplicate
             dotnet nuget push MorganStanley.ComposeUI.Fdc3.DesktopAgent.Shared.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ env.nuget_source }} --skip-duplicate
             dotnet nuget push MorganStanley.ComposeUI.ModuleLoader.Abstractions.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ env.nuget_source }} --skip-duplicate
             dotnet nuget push MorganStanley.ComposeUI.Utilities.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ env.nuget_source }} --skip-duplicate
